//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaAlmacenes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int EmpleadoID { get; set; }
        public string DPI { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> CantidadHijos { get; set; }
        public decimal SalarioBase { get; set; }
        public decimal BonoDecreto { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
